const skills: string[] = [
    "Python",
    "PyTorch",
    "TensorFlow",
    "Pandas",
    "NumPy",
    "Flask",
    "FastAPI",
    "Langchain",
    "Streamlit",
    "Scikit-learn",
    "JavaScript",
    "TypeScript",
    "React",
    "Node.js",
    "Express.js",
    "MongoDB",
    "SQL",
    "Pinecone",
    "Git/GitHub",
    "REST APIs",
    "Next.js",
    "Tailwind CSS",
    "Docker",
    "CI/CD",
    "MLflow",
    "MLops",
];

export default skills;